---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundry-licenses
  labels:
    app.kubernetes.io/name: foundry-licenses
    app.kubernetes.io/component: foundry
    app.kubernetes.io/part-of: foundry
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-foundry
    kind: ClusterSecretStore
  target:
    name: foundry-licenses
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /license
        property: foundry-license-key
      secretKey: foundry-license-key
