---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundry-credentials
  labels:
    app.kubernetes.io/name: foundry-credentials
    app.kubernetes.io/component: foundry
    app.kubernetes.io/part-of: foundry
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-foundry
    kind: ClusterSecretStore
  target:
    name: foundry-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /credentials
        property: username
      secretKey: foundry-username
    - remoteRef:
        conversionStrategy: Default
        key: /credentials
        property: password
      secretKey: foundry-password
