---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saltysausage-foundryvtt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-foundry
    kind: ClusterSecretStore
  target:
    name: saltysausage-foundryvtt
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /credentials
        property: username
      secretKey: foundry-username
    - remoteRef:
        conversionStrategy: Default
        key: /credentials
        property: password
      secretKey: foundry-password
    - remoteRef:
        conversionStrategy: Default
        key: /license
        property: saltysausage-license-key
      secretKey: foundry-license-key
    - remoteRef:
        conversionStrategy: Default
        key: /settings
        property: saltysausge-admin-key
      secretKey: admin-key
    - remoteRef:
        conversionStrategy: Default
        key: /settings
        property: saltysausage-aws-config
      secretKey: awsConfig.json
