---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddb-proxy
  labels:
    app.kubernetes.io/name: ddb-proxy
    app.kubernetes.io/component: ddb-proxy
    app.kubernetes.io/part-of: foundry
    app.kubernetes.io/managed-by: argocd
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: ddb-proxy
      app.kubernetes.io/component: ddb-proxy
      app.kubernetes.io/part-of: foundry
      app.kubernetes.io/managed-by: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ddb-proxy
        app.kubernetes.io/component: ddb-proxy
        app.kubernetes.io/part-of: foundry
        app.kubernetes.io/managed-by: argocd
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: ddb-proxy
          image: ghcr.io/mrprimate/ddb-proxy:0.0.25 # renovate
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          livenessProbe:
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 100
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /ping
              port: http
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            privileged: false
            capabilities:
              drop:
                - ALL
