---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
spec:
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
    spec:
      containers:
        - name: foundry
          image: felddy/foundryvtt:v12.328.0 # renovate
          resources:
            requests:
              cpu: 1000m
              memory: 2000Gi
            limits:
              memory: 4000Gi
          ports:
            - containerPort: 30000
