---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
spec:
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: container-cache
          emptyDir: {}
      containers:
        - name: foundry
          image: felddy/foundryvtt:12.328.0 # renovate
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              memory: 4Gi
          volumeMounts:
            - mountPath: /data/container_cache
              name: container-cache
          ports:
            - containerPort: 30000
              name: web
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
