---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-foundry-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foundry
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: foundry
  source:
    repoURL: https://charts.derwitt.dev
    targetRevision: 0.1.1
    chart: foundryvtt
    helm:
      releaseName: test
      values: |

        enableTelemetry: true
        existingSecret:
          containsLicenseKey: true
          containsAwsConfig: true
        storage:
          className: longhorn
        resources:
          requests:
            cpu: 40m
            memory: 512Mi
          limits:
            memory: 512Mi
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
            traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
            external-dns.alpha.kubernetes.io/target: 172.30.0.5, 2a01:4f8:c012:f0b3:ac1e::5
          hosts:
            - host: vtt.home.derwitt.net
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - vtt.home.derwitt.net
              secretName: foundry-ingress-tls
