# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/main/api/jsonschema/schema.json
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: code-and-quest-offsite-backup
spec:
  schedule: "30 3 * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 7
  workflowSpec:
    entrypoint: main
    onExit: exit-handler
    podMetadata:
      labels:
        network-policy/allow-minio-traffic: apply
        network-policy/allow-kube-apiserver-traffic: apply
        network-policy/allow-backup-egress: apply
    artifactGC:
      strategy: OnWorkflowDeletion
      serviceAccountName: foundry-workflows
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    templates:
      - name: main
        dag:
          tasks:
            - name: backup
              templateRef:
                name: foundry-backup-template
                template: main
              arguments:
                parameters:
                  - name: instance
                    value: code-and-quest-foundryvtt
                  - name: restic-hostname
                    value: code-and-quest-foundryvtt
                  - name: pvc-name
                    value: data-code-and-quest-foundryvtt-0

      - name: exit-handler
        steps:
          - - name: scale-up
              arguments:
                parameters:
                  - name: name
                    value: code-and-quest-foundryvtt
                  - name: replicaCount
                    value: "1"
                  - name: type
                    value: statefulset
              templateRef:
                template: scale-workload
                name: scale-workload
