# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/main/api/jsonschema/schema.json
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: scale-workload
spec:
  entrypoint: scale-workload
  artifactGC:
    strategy: OnWorkflowDeletion
    serviceAccountName: foundry-workflows
    podMetadata:
      labels:
        network-policy/allow-minio-traffic: apply
        network-policy/allow-kube-apiserver-traffic: apply
  podGC:
    strategy: OnWorkflowSuccess
  podMetadata:
    labels:
      network-policy/allow-kube-apiserver-traffic: apply
      network-policy/allow-minio-traffic: apply
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  arguments:
    parameters:
      - name: replicaCount
      - name: name
        default: foundry
      - name: type
        default: statefulset
  templates:
    - name: scale-workload
      serviceAccountName: foundry-workflows
      automountServiceAccountToken: true
      inputs:
        parameters:
          - name: replicaCount
          - name: name
          - name: type
      container:
        image: denniswitt/devops-tools:1.0.0 # renovate
        command:
          - sh
          - -c
        args:
          - |
            set -eu

            kubectl scale --replicas={{inputs.parameters.replicaCount}} -n foundry {{inputs.parameters.type}}/{{inputs.parameters.name}}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
