---
name: lint

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release/**

jobs:
  lint:
    runs-on: debian-13
    permissions:
      contents: read
    steps:
      - uses: https://git.derwitt.site/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: setup uv
        uses: https://git.derwitt.site/actions/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: install yamllint
        run: |
          uv tool install yamllint@${YAMLLINT_VERSION}
          uv tool list
        env:
          YAMLLINT_VERSION: 1.38.0 # datasource=pypi depName=yamllint packageName=yamllint versioning=semver

      - name: lint
        run: |
          yamllint -c .yamllint .
