---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-scaler
rules:
  - verbs:
      - get
    resources:
      - deployments
    apiGroups:
      - apps
  - verbs:
      - patch
      - update
    resources:
      - deployments/scale
    apiGroups:
      - apps
