---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-scaler
subjects:
  - kind: ServiceAccount
    name: foundry-workflows
