---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: foundry-workflows-executor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-executor
subjects:
  - kind: ServiceAccount
    name: foundry-workflows
