---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
  labels:
    app.kubernetes.io/name: foundry-data-pvc
    app.kubernetes.io/component: foundry
    app.kubernetes.io/part-of: foundry
    app.kubernetes.io/managed-by: argocd
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
