---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-backup-egress
spec:
  endpointSelector:
    matchLabels:
      network-policy/allow-backup-egress: apply
  egress:
    - toFQDNs:
        - matchName: "backups92217735.blob.core.windows.net"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
