name: lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint
